version: 2
updates:
- package-ecosystem: npm
  directory: "/swr-lab-push-intern"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/swr-lab-app-domains"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/audiogram"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/swr-lab-stackdriver-log"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/swr-lab-dashboard"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
